baseurl = "https://www.jotaen.net"
languageCode = "en-us"
disablePathToLower = true
ignoreFiles = [ "\\.scss$", "credits\\.pdf$" ]
disableKinds = ["taxonomy","taxonomyTerm"]

[blackfriday]
  smartypants = false
  smartDashes = false
  latexDashes = false
  
