baseurl = "https://www.jotaen.net"
languageCode = "en-us"
disablePathToLower = true
ignoreFiles = [ "\\.scss$", "credits\\.pdf$" ]
disableKinds = ["taxonomy","taxonomyTerm"]
buildFuture = true
enableRobotsTXT = true
  
[markup.goldmark.renderer]
unsafe = true