name: Deploy
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build website
      run: make public
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@0ebd6f1ab92511ceefba39e1a2fe677521f892ad
      env:
        PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCLOUD_KEY }}
      with:
        args: deploy --only hosting
    - name: Send slack notification
      env:
        SLACK_WEBHOOKURL: ${{ secrets.SLACK_WEBHOOKURL }}
      run: |
        curl \
          -X "POST" \
          $SLACK_WEBHOOKURL \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d $'{
            "icon_emoji": ":rocket:",
            "text": "Deployment okay [`'${GITHUB_SHA:0:7}'`]",
            "username": "Deployment"
          }'

